feat(build): use grafana officials binaries
CleverCloud/grafana-example pull request #2
Opened 2021-06-02 15:18 UTC by aurrelhebert

2021-06-09 08:16 UTC, aurrelhebert commented
cc @BlackYoup cc @urcadox

2021-06-09 09:57 UTC, BlackYoup requested changes
I've made a few suggestions, let me know what you think of them.

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +# How to set up Grafana on Clever-Cloud
It was well written :) It's `Clever Cloud`

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +6. Add `GF_PLUGIN_DIR` environnement variable with `/home/bas/APP_ID/grafana/data/plugins` to use local cloned plugins.
Didn't you manage to make this work with a relative path? If we could avoid having the app id written there, it could be great.

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +7. You can now build and start the clever-cloud application, be aware however that if you restart it your data will not be persisted (see next section to learn how to persist data).
`Clever Cloud` (or you could get rid of it I guess)

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +8. To change grafana configuration through environment variables please check [grafana configuration page](https://grafana.com/docs/grafana/latest/administration/configuration/).
```suggestion
8. To configure Grafana through environment variables please check [grafana configuration page](https://grafana.com/docs/grafana/latest/administration/configuration/).
```

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +1. Create your database add-on on clever-cloud and link it to the application, you can check our addon [documentation](https://www.clever-cloud.com/doc/getting-started/quickstart/#create-your-first-a
```suggestion
1. Create your database add-on on Clever Cloud and link it to the application, you can check our [documentation](https://www.clever-cloud.com/doc/getting-started/quickstart/#create-your-first-add-on).
```

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +2. In your application environment variables you should now see the information you need to connect to your db.
```suggestion
2. In your application environment variables you should now see the information you need to connect to your database.
```

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +3. Link them to grafana, to do this you need to create a few environment variables (replace what's in '<>' with the actual value):
```suggestion
3. Link your add-on to your Grafana application. To do this you need to create a few environment variables (replace what's in '<>' with the actual value):
```

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +1. Use a fork of this repository as a Node.js application. It will download and run Grafana using the root `package.json` file. The install script `build.sh` will download grafana and its plugins and
I think the first item should be `fork this repository`. Then second should be create the application, with a link to https://www.clever-cloud.com/doc/getting-started/by-language/node/#create-an-application-on-clever-cloud

2021-06-09 09:57 UTC, BlackYoup commented on README.md
> +3. Add ```GRAFANA_VERSION``` and ```GRAFANA_SHA_256``` environment variables. The grafana dowload page is [here](https://grafana.com/grafana/download).
```suggestion
3. Add ```GRAFANA_VERSION``` and ```GRAFANA_SHA_256``` environment variables. You can find these values on the [Grafana download page](https://grafana.com/grafana/download).
```

2021-06-11 10:46 UTC, BlackYoup requested changes
Once this last comment is fixed (sorry, I missed it), we can merge this :)

2021-06-11 10:46 UTC, BlackYoup commented on README.md
> +8. To configure Grafana through environment variables please check [grafana configuration page](https://grafana.com/docs/grafana/latest/administration/configuration/).
There is twice `8` :grin:

2021-06-15 10:50 UTC, merged

2021-06-15 10:50 UTC, BlackYoup commented
Thanks :)